/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.erenresortmvn.Gui;

import com.erenresortmvn.Dal.tblmusteriDAO;
import com.erenresortmvn.Models.tblmusteri;
import com.erenresortmvn.Util.StaticValues;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vektorel
 */
public class frmMusteriListesi extends javax.swing.JFrame {

    tblmusteri mst = new tblmusteri();
    tblmusteriDAO dbmusteri = new tblmusteriDAO();
            
    /**
     * Creates new form frmMusteriListesi
     */
    public frmMusteriListesi() {
        initComponents();
        tabloDoldur();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txttckimlik = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabloMusteri = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txttckimlik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttckimlikKeyPressed(evt);
            }
        });

        TabloMusteri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tc Kimlik", "Müşteri Ad", "Müşteri Soyad", "id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabloMusteri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabloMusteriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabloMusteri);

        jButton1.setText("Müşteri Ekle");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txttckimlik, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttckimlik, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TabloMusteriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabloMusteriMouseClicked
        int secilen = TabloMusteri.getSelectedRow();
        int id = Integer.parseInt(TabloMusteri.getValueAt(secilen, 3).toString());
        tblmusteriDAO db  = new tblmusteriDAO();
        StaticValues.mst = db.bul(id, mst);
        this.setVisible(false);
        
    }//GEN-LAST:event_TabloMusteriMouseClicked

    private void txttckimlikKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttckimlikKeyPressed
        tabloDoldur(dbmusteri.musteriAra(txttckimlik.getText()));
    }//GEN-LAST:event_txttckimlikKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMusteriListesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMusteriListesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMusteriListesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMusteriListesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMusteriListesi().setVisible(true);
            }
        });
    }

    public void tabloDoldur(){
        tablotemizle();
        tblmusteriDAO db = new tblmusteriDAO();
        int i=0;
        for (tblmusteri item : db.listele(mst)) {
            satirekle();
         TabloMusteri.setValueAt(item.getTckimlik(), i, 0);
         TabloMusteri.setValueAt(item.getAd(), i, 1);
         TabloMusteri.setValueAt(item.getSoyad(), i, 2);
         TabloMusteri.setValueAt(item.getId(), i, 3);
         
         
         i++;
        }
        
    }
    
       public void tabloDoldur(List<tblmusteri> lst){
      tablotemizle();
        int i=0;
        for (tblmusteri item : lst) {
            satirekle();
         TabloMusteri.setValueAt(item.getTckimlik(), i, 0);
         TabloMusteri.setValueAt(item.getAd(), i, 1);
         TabloMusteri.setValueAt(item.getSoyad(), i, 2);
         TabloMusteri.setValueAt(item.getId(), i, 3);
         
         
         i++;
        }
        
    }
    public void tablotemizle(){
     DefaultTableModel dmt = (DefaultTableModel)this.TabloMusteri.getModel();
     dmt.getDataVector().removeAllElements();
      this.TabloMusteri.repaint();
    }
    
     public void satirekle(){
            DefaultTableModel dmt = (DefaultTableModel)this.TabloMusteri.getModel();
            dmt.setRowCount(dmt.getRowCount()+1);
            this.TabloMusteri.repaint();
  }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabloMusteri;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txttckimlik;
    // End of variables declaration//GEN-END:variables
}
