/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.erenresortmvn.Gui;

import javax.swing.JOptionPane;

/**
 *
 * @author AB175103
 */
public class frmMainPage extends javax.swing.JFrame {

    /**
     * Creates new form frmMainPage
     */
    public frmMainPage() {
        initComponents();
        lblRzvCizgi.setVisible(false);
        lblFiyatCizgi.setVisible(false);
        lblOdaCizgi.setVisible(false);
        lblOzellikCizgi.setVisible(false);
        lblPersCizgi.setVisible(false);
        lblodemeCizgi.setVisible(false);
        lblmusteriCizgi.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblRezvTanim = new javax.swing.JLabel();
        lblRzvCizgi = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblMusteriKayit = new javax.swing.JLabel();
        lblmusteriCizgi = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblPesonelKayit = new javax.swing.JLabel();
        lblPersCizgi = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblOdaKayit = new javax.swing.JLabel();
        lblOdaCizgi = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblOzellikKayit = new javax.swing.JLabel();
        lblOzellikCizgi = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblFiyatTanimlama = new javax.swing.JLabel();
        lblFiyatCizgi = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblOdemeKAyit = new javax.swing.JLabel();
        lblodemeCizgi = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pn4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pn1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pn2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pn3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        pn8 = new javax.swing.JPanel();
        pn7 = new javax.swing.JPanel();
        pn6 = new javax.swing.JPanel();
        pn5 = new javax.swing.JPanel();
        pn12 = new javax.swing.JPanel();
        pn11 = new javax.swing.JPanel();
        pn10 = new javax.swing.JPanel();
        pn9 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(53, 33, 89));

        jPanel2.setBackground(new java.awt.Color(85, 65, 118));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/erenresortmvn/Media/reservation.png"))); // NOI18N
        jLabel3.setToolTipText("");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        lblRezvTanim.setBackground(new java.awt.Color(204, 204, 204));
        lblRezvTanim.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblRezvTanim.setForeground(new java.awt.Color(204, 204, 204));
        lblRezvTanim.setText("Rezervasyon Tanımlama");
        jPanel2.add(lblRezvTanim, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 167, -1));

        lblRzvCizgi.setForeground(new java.awt.Color(255, 255, 255));
        lblRzvCizgi.setText("_____________________________");
        jPanel2.add(lblRzvCizgi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 24, 218, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/erenresortmvn/Media/Hotel Star_104px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("EREN RESORT");

        jPanel3.setBackground(new java.awt.Color(85, 65, 118));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMusteriKayit.setForeground(new java.awt.Color(204, 204, 204));
        lblMusteriKayit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/erenresortmvn/Media/customer.png"))); // NOI18N
        lblMusteriKayit.setText("  Müşteri Kayıt");
        jPanel3.add(lblMusteriKayit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 184, -1));

        lblmusteriCizgi.setForeground(new java.awt.Color(255, 255, 255));
        lblmusteriCizgi.setText("_____________________________");
        jPanel3.add(lblmusteriCizgi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 24, 220, 20));

        jPanel4.setBackground(new java.awt.Color(85, 65, 118));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPesonelKayit.setForeground(new java.awt.Color(204, 204, 204));
        lblPesonelKayit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/erenresortmvn/Media/staff.png"))); // NOI18N
        lblPesonelKayit.setText("  Personel Kayıt");
        jPanel4.add(lblPesonelKayit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 160, -1));

        lblPersCizgi.setForeground(new java.awt.Color(255, 255, 255));
        lblPersCizgi.setText("_____________________________");
        jPanel4.add(lblPersCizgi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 24, 220, 20));

        jPanel5.setBackground(new java.awt.Color(85, 65, 118));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOdaKayit.setForeground(new java.awt.Color(204, 204, 204));
        lblOdaKayit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/erenresortmvn/Media/room.png"))); // NOI18N
        lblOdaKayit.setText("  Oda Kayıt");
        jPanel5.add(lblOdaKayit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 120, -1));

        lblOdaCizgi.setForeground(new java.awt.Color(255, 255, 255));
        lblOdaCizgi.setText("_____________________________");
        jPanel5.add(lblOdaCizgi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 24, 220, 20));

        jPanel6.setBackground(new java.awt.Color(85, 65, 118));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOzellikKayit.setForeground(new java.awt.Color(204, 204, 204));
        lblOzellikKayit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/erenresortmvn/Media/property.png"))); // NOI18N
        lblOzellikKayit.setText("  Özellik Tanımlama");
        jPanel6.add(lblOzellikKayit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1, -1, -1));

        lblOzellikCizgi.setForeground(new java.awt.Color(255, 255, 255));
        lblOzellikCizgi.setText("_____________________________");
        jPanel6.add(lblOzellikCizgi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 220, 20));

        jPanel7.setBackground(new java.awt.Color(85, 65, 118));
        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel7MouseExited(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFiyatTanimlama.setForeground(new java.awt.Color(204, 204, 204));
        lblFiyatTanimlama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/erenresortmvn/Media/price.png"))); // NOI18N
        lblFiyatTanimlama.setText("  Fiyat Tanımlama");
        jPanel7.add(lblFiyatTanimlama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        lblFiyatCizgi.setForeground(new java.awt.Color(255, 255, 255));
        lblFiyatCizgi.setText("_____________________________");
        jPanel7.add(lblFiyatCizgi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 220, 20));

        jPanel8.setBackground(new java.awt.Color(85, 65, 118));
        jPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel8MouseExited(evt);
            }
        });
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOdemeKAyit.setForeground(new java.awt.Color(204, 204, 204));
        lblOdemeKAyit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/erenresortmvn/Media/payment.png"))); // NOI18N
        lblOdemeKAyit.setText("  Ödeme Al");
        jPanel8.add(lblOdemeKAyit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        lblodemeCizgi.setForeground(new java.awt.Color(255, 255, 255));
        lblodemeCizgi.setText("_____________________________");
        jPanel8.add(lblodemeCizgi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 24, 220, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(110, 89, 200));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("SEFA");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("OTEL YÖNETİM VE TAKİP SİSTEMİ");
        jLabel5.setToolTipText("");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 49, -1, -1));

        pn4.setBackground(new java.awt.Color(255, 255, 255));
        pn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn4MouseExited(evt);
            }
        });
        pn4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(pn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 185, 180));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("X");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 9, 22, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("_");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 9, -1, -1));

        jLabel8.setText("Otelde Toplam 12 Oda bulunmaktadır, 5 Oda temizlenmektedir. Toplam 33 Kişi otelde konaklamaktadır.");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 780, 40));

        pn1.setBackground(new java.awt.Color(255, 255, 255));
        pn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn1MouseExited(evt);
            }
        });
        pn1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("101 Numaralı Oda");
        pn1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/erenresortmvn/Media/roombos2.png"))); // NOI18N
        pn1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 255, 0));
        jLabel13.setText("BOŞ");
        pn1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        jPanel9.add(pn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 185, 180));

        pn2.setBackground(new java.awt.Color(255, 255, 255));
        pn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn2MouseExited(evt);
            }
        });
        pn2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("102 Numaralı Oda");
        pn2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/erenresortmvn/Media/roomtemizlik.png"))); // NOI18N
        pn2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 204, 102));
        jLabel14.setText("TMZ");
        pn2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        jPanel9.add(pn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 185, 180));

        pn3.setBackground(new java.awt.Color(255, 255, 255));
        pn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn3MouseExited(evt);
            }
        });
        pn3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("103 Numaralı Oda");
        pn3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("DOLU");
        pn3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/erenresortmvn/Media/roomdolu.png"))); // NOI18N
        pn3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 100, 100));

        jLabel18.setForeground(new java.awt.Color(51, 51, 0));
        jLabel18.setText("Kalan Kişi Sayısı");
        pn3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel19.setForeground(new java.awt.Color(51, 51, 0));
        jLabel19.setText("Yetişkin Sayısı");
        pn3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 100, -1));

        jLabel20.setForeground(new java.awt.Color(51, 51, 0));
        jLabel20.setText("Çocuk Sayısı");
        jLabel20.setToolTipText("");
        pn3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, -1));

        jLabel21.setForeground(new java.awt.Color(51, 51, 0));
        jLabel21.setText(": 3");
        pn3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jLabel22.setForeground(new java.awt.Color(51, 51, 0));
        jLabel22.setText(": 2");
        pn3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jLabel23.setForeground(new java.awt.Color(51, 51, 0));
        jLabel23.setText(": 1");
        pn3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jPanel9.add(pn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 185, 180));

        pn8.setBackground(new java.awt.Color(255, 255, 255));
        pn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn8MouseExited(evt);
            }
        });
        pn8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(pn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 185, 170));

        pn7.setBackground(new java.awt.Color(255, 255, 255));
        pn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn7MouseExited(evt);
            }
        });
        pn7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(pn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 185, 170));

        pn6.setBackground(new java.awt.Color(255, 255, 255));
        pn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn6MouseExited(evt);
            }
        });
        pn6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(pn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 185, 170));

        pn5.setBackground(new java.awt.Color(255, 255, 255));
        pn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn5MouseExited(evt);
            }
        });
        pn5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(pn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 185, 170));

        pn12.setBackground(new java.awt.Color(255, 255, 255));
        pn12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn12MouseExited(evt);
            }
        });
        pn12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(pn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 620, 185, 160));

        pn11.setBackground(new java.awt.Color(255, 255, 255));
        pn11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn11MouseExited(evt);
            }
        });
        pn11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(pn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 620, 185, 160));

        pn10.setBackground(new java.awt.Color(255, 255, 255));
        pn10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn10MouseExited(evt);
            }
        });
        pn10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(pn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 620, 185, 160));

        pn9.setBackground(new java.awt.Color(255, 255, 255));
        pn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn9MouseExited(evt);
            }
        });
        pn9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(pn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 185, 160));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 780, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        
        lblRzvCizgi.setVisible(true);
      
        
        lblRezvTanim.setForeground(new java.awt.Color(240, 240, 240));
        
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
        lblRezvTanim.setForeground(new java.awt.Color(204, 204, 204));
        lblRzvCizgi.setVisible(false);
    }//GEN-LAST:event_jPanel2MouseExited

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        lblMusteriKayit.setForeground(new java.awt.Color(240, 240, 240));
        lblmusteriCizgi.setVisible(true);
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        lblMusteriKayit.setForeground(new java.awt.Color(204, 204, 204));
        lblmusteriCizgi.setVisible(false);
    }//GEN-LAST:event_jPanel3MouseExited

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        lblPesonelKayit.setForeground(new java.awt.Color(240, 240, 240));
        lblPersCizgi.setVisible(true);
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
       lblPesonelKayit.setForeground(new java.awt.Color(204, 204, 204));
        lblPersCizgi.setVisible(false);
    }//GEN-LAST:event_jPanel4MouseExited

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
          lblOdaKayit.setForeground(new java.awt.Color(240, 240, 240));
        lblOdaCizgi.setVisible(true);
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
          lblOdaKayit.setForeground(new java.awt.Color(204, 204, 204));
        lblOdaCizgi.setVisible(false);
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
            lblOzellikKayit.setForeground(new java.awt.Color(240, 240, 240));
        lblOzellikCizgi.setVisible(true);
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
          lblOzellikKayit.setForeground(new java.awt.Color(204, 204, 204));
        lblOzellikCizgi.setVisible(false);
    }//GEN-LAST:event_jPanel6MouseExited

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered
        lblFiyatTanimlama.setForeground(new java.awt.Color(240, 240, 240));
        lblFiyatCizgi.setVisible(true);
    }//GEN-LAST:event_jPanel7MouseEntered

    private void jPanel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseExited
        lblFiyatTanimlama.setForeground(new java.awt.Color(204, 204, 204));
        lblFiyatCizgi.setVisible(false);
    }//GEN-LAST:event_jPanel7MouseExited

    private void jPanel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseEntered
         lblOdemeKAyit.setForeground(new java.awt.Color(240, 240, 240));
        lblodemeCizgi.setVisible(true);
    }//GEN-LAST:event_jPanel8MouseEntered

    private void jPanel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseExited
       lblOdemeKAyit.setForeground(new java.awt.Color(204, 204, 204));
        lblodemeCizgi.setVisible(false);
    }//GEN-LAST:event_jPanel8MouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void pn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn1MouseEntered
          pn1.setBackground(new java.awt.Color(204, 204, 255));
    }//GEN-LAST:event_pn1MouseEntered

    private void pn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn1MouseExited
          pn1.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_pn1MouseExited

    private void pn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn2MouseEntered
          pn2.setBackground(new java.awt.Color(204, 204, 255));
    }//GEN-LAST:event_pn2MouseEntered

    private void pn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn2MouseExited
          pn2.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_pn2MouseExited

    private void pn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn3MouseEntered
          pn3.setBackground(new java.awt.Color(204, 204, 255));
    }//GEN-LAST:event_pn3MouseEntered

    private void pn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn3MouseExited
        pn3.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_pn3MouseExited

    private void pn4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn4MouseEntered
         pn4.setBackground(new java.awt.Color(204, 204, 255));
    }//GEN-LAST:event_pn4MouseEntered

    private void pn4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn4MouseExited
        pn4.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_pn4MouseExited

    private void pn5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn5MouseEntered
         pn5.setBackground(new java.awt.Color(204, 204, 255));
    }//GEN-LAST:event_pn5MouseEntered

    private void pn5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn5MouseExited
         pn5.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_pn5MouseExited

    private void pn6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn6MouseEntered
       pn6.setBackground(new java.awt.Color(204, 204, 255));
    }//GEN-LAST:event_pn6MouseEntered

    private void pn6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn6MouseExited
         pn6.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_pn6MouseExited

    private void pn7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn7MouseEntered
         pn7.setBackground(new java.awt.Color(204, 204, 255));
    }//GEN-LAST:event_pn7MouseEntered

    private void pn7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn7MouseExited
          pn7.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_pn7MouseExited

    private void pn8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn8MouseEntered
         pn8.setBackground(new java.awt.Color(204, 204, 255));
    }//GEN-LAST:event_pn8MouseEntered

    private void pn8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn8MouseExited
         pn8.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_pn8MouseExited

    private void pn9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn9MouseEntered
         pn9.setBackground(new java.awt.Color(204, 204, 255));
    }//GEN-LAST:event_pn9MouseEntered

    private void pn9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn9MouseExited
         pn9.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_pn9MouseExited

    private void pn10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn10MouseEntered
        pn10.setBackground(new java.awt.Color(204, 204, 255));
    }//GEN-LAST:event_pn10MouseEntered

    private void pn10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn10MouseExited
         pn10.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_pn10MouseExited

    private void pn11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn11MouseEntered
        pn11.setBackground(new java.awt.Color(204, 204, 255));
    }//GEN-LAST:event_pn11MouseEntered

    private void pn11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn11MouseExited
          pn11.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_pn11MouseExited

    private void pn12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn12MouseEntered
        pn12.setBackground(new java.awt.Color(204, 204, 255));
    }//GEN-LAST:event_pn12MouseEntered

    private void pn12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn12MouseExited
        pn12.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_pn12MouseExited

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        frmMusteriKayit frmmusteri = new frmMusteriKayit();
        frmmusteri.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
       frmOdatanimlama frmoda = new frmOdatanimlama();
       frmoda.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
     frmOdaOzellikTanimlama frmozellik = new frmOdaOzellikTanimlama();
     frmozellik.setVisible(rootPaneCheckingEnabled);
             
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        frmFiyatTanimlama frmfiyat = new frmFiyatTanimlama();
        frmfiyat.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        frmPersonelKayit frmpers = new frmPersonelKayit();
        frmpers.setVisible(rootPaneCheckingEnabled);
                
    }//GEN-LAST:event_jPanel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblFiyatCizgi;
    private javax.swing.JLabel lblFiyatTanimlama;
    private javax.swing.JLabel lblMusteriKayit;
    private javax.swing.JLabel lblOdaCizgi;
    private javax.swing.JLabel lblOdaKayit;
    private javax.swing.JLabel lblOdemeKAyit;
    private javax.swing.JLabel lblOzellikCizgi;
    private javax.swing.JLabel lblOzellikKayit;
    private javax.swing.JLabel lblPersCizgi;
    private javax.swing.JLabel lblPesonelKayit;
    private javax.swing.JLabel lblRezvTanim;
    private javax.swing.JLabel lblRzvCizgi;
    private javax.swing.JLabel lblmusteriCizgi;
    private javax.swing.JLabel lblodemeCizgi;
    private javax.swing.JPanel pn1;
    private javax.swing.JPanel pn10;
    private javax.swing.JPanel pn11;
    private javax.swing.JPanel pn12;
    private javax.swing.JPanel pn2;
    private javax.swing.JPanel pn3;
    private javax.swing.JPanel pn4;
    private javax.swing.JPanel pn5;
    private javax.swing.JPanel pn6;
    private javax.swing.JPanel pn7;
    private javax.swing.JPanel pn8;
    private javax.swing.JPanel pn9;
    // End of variables declaration//GEN-END:variables
}
