/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.erenresortmvn.Gui;
import com.erenresortmvn.Dal.tblodaDAO;
import com.erenresortmvn.Models.tbloda;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vektorel
 */
public class frmOdatanimlama extends javax.swing.JFrame {

     public static int secilenid;
     public int modelsecilen;
    List<tbloda> musterioda=new ArrayList<tbloda>();
    
    tblodaDAO db= new tblodaDAO();
    
    /**
     * Creates new form frmMain
     */
    public frmOdatanimlama() {
        initComponents();
         musterioda = db.listele(new tbloda());
          tabloyukle();
         tbloda.setDefaultEditor(Object.class, null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuDuzenle = new javax.swing.JPopupMenu();
        jMenuItemSil = new javax.swing.JMenuItem();
        jMenuItemDuzenle = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbloda = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtkapasite = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnkayit = new javax.swing.JButton();
        btnguncelle = new javax.swing.JButton();
        btniptal = new javax.swing.JButton();
        btnyenikayit = new javax.swing.JButton();
        cmbkat = new javax.swing.JComboBox<>();
        cmbdurum = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jMenuItemSil.setText("Sil");
        jMenuItemSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSilActionPerformed(evt);
            }
        });
        jPopupMenuDuzenle.add(jMenuItemSil);

        jMenuItemDuzenle.setText("Düzenle");
        jMenuItemDuzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDuzenleActionPerformed(evt);
            }
        });
        jPopupMenuDuzenle.add(jMenuItemDuzenle);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbloda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ad", "Kapasite", "Kat", "Durumu", "id"
            }
        ));
        tbloda.setComponentPopupMenu(jPopupMenuDuzenle);
        jScrollPane1.setViewportView(tbloda);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 586, 480));

        jPanel1.setBackground(new java.awt.Color(65, 131, 215));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ad*");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setText("Kat*");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txtad.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(txtad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 137, -1));

        jLabel3.setText("Kapasite*");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txtkapasite.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(txtkapasite, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 137, -1));

        jLabel4.setText("Durumu*");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        btnkayit.setBackground(new java.awt.Color(148, 124, 176));
        btnkayit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/erenresortmvn/Media/Save_50px.png"))); // NOI18N
        btnkayit.setText("Kaydet");
        btnkayit.setEnabled(false);
        btnkayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkayitActionPerformed(evt);
            }
        });
        jPanel1.add(btnkayit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 210, -1));

        btnguncelle.setBackground(new java.awt.Color(148, 124, 176));
        btnguncelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/erenresortmvn/Media/Update_50px.png"))); // NOI18N
        btnguncelle.setText("Güncelle");
        btnguncelle.setEnabled(false);
        btnguncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguncelleActionPerformed(evt);
            }
        });
        jPanel1.add(btnguncelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 210, -1));

        btniptal.setBackground(new java.awt.Color(148, 124, 176));
        btniptal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/erenresortmvn/Media/Cancel_50px.png"))); // NOI18N
        btniptal.setText("İptal");
        btniptal.setEnabled(false);
        btniptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniptalActionPerformed(evt);
            }
        });
        jPanel1.add(btniptal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 210, -1));

        btnyenikayit.setBackground(new java.awt.Color(148, 124, 176));
        btnyenikayit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/erenresortmvn/Media/New_50px.png"))); // NOI18N
        btnyenikayit.setText("Yeni Kayıt");
        btnyenikayit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnyenikayit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnyenikayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnyenikayitActionPerformed(evt);
            }
        });
        jPanel1.add(btnyenikayit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 210, 60));

        cmbkat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        jPanel1.add(cmbkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 137, -1));

        cmbdurum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BOŞ", "DOLU" }));
        jPanel1.add(cmbdurum, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 137, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 550));

        jPanel2.setBackground(new java.awt.Color(65, 131, 215));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Yeni Oda Tanımlama Formu");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 2, -1, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 40, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 590, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnkayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkayitActionPerformed
        if(txtad.getText().equals("")|| txtkapasite.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Boş alanları doldurun");
        }
        else
        {
            tbloda tbl= new tbloda();
            tbl.setAd(txtad.getText());
            tbl.setKapasite(Integer.parseInt(txtkapasite.getText()));
            tbl.setKat(cmbkat.getSelectedItem().toString());
            tbl.setDurumu(cmbdurum.getSelectedItem().toString());
            musterioda.add(tbl);

            db.kaydet(tbl);
            tabloyukle();
            txtkapat();
            temizle();
            btnyenikayit.setEnabled(true);
            btnkayit.setEnabled(false);
            btniptal.setEnabled(false);
           
        }

    }//GEN-LAST:event_btnkayitActionPerformed

    private void btnguncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguncelleActionPerformed
        tbloda temp= new tbloda();
        temp.setAd(txtad.getText());
        temp.setKapasite(Integer.parseInt(txtkapasite.getText()));
        temp.setKat(cmbkat.getSelectedItem().toString());
        temp.setDurumu(cmbdurum.getSelectedItem().toString());
        temp.setId(secilenid);
        musterioda.set(modelsecilen,temp);
        db.duzenle(temp);
        tabloyukle();
        temizle();
        btnyenikayit.setEnabled(true);
        btnguncelle.setEnabled(false);
        btniptal.setEnabled(false);

    }//GEN-LAST:event_btnguncelleActionPerformed

    private void btniptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniptalActionPerformed
        temizle();
        btnyenikayit.setEnabled(true);
        btnkayit.setEnabled(false);
        btnguncelle.setEnabled(false);
        btniptal.setEnabled(false);
    }//GEN-LAST:event_btniptalActionPerformed

    private void btnyenikayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnyenikayitActionPerformed

        btnyenikayit.setEnabled(false);
        btnkayit.setEnabled(true);
        btniptal.setEnabled(true);
        txtac();

    }//GEN-LAST:event_btnyenikayitActionPerformed

    private void jMenuItemSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSilActionPerformed
         int reply = JOptionPane.showConfirmDialog(null, "İlgili Kaydı silmek istiyor musunuz?",
              "UYARI", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            
        int secilen = tbloda.getSelectedRow();
        satirsil(secilen);
        //db.sil(secilen);
        tabloyukle();
        
        }
        else {
           JOptionPane.showMessageDialog(null, "İşlem İptal Edilmiştir.");
           
        }
    }//GEN-LAST:event_jMenuItemSilActionPerformed

    private void jMenuItemDuzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDuzenleActionPerformed
      
           int secilen = tbloda.getSelectedRow();
           modelsecilen = secilen;
      secilenid =Integer.parseInt(tbloda.getValueAt(secilen, 4).toString());
        txtad.setText(tbloda.getValueAt(secilen, 0).toString());
       txtkapasite.setText(tbloda.getValueAt(secilen,1).toString());
   cmbkat.setSelectedItem(tbloda.getValueAt(secilen,2).toString());
   cmbdurum.setSelectedItem(tbloda.getValueAt(secilen,3).toString());
   btnkayit.setEnabled(false);
    btnyenikayit.setEnabled(false);
        btnguncelle.setEnabled(true);
        btniptal.setEnabled(true);  
        txtac();
    }//GEN-LAST:event_jMenuItemDuzenleActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
       this.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmOdatanimlama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmOdatanimlama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmOdatanimlama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmOdatanimlama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmOdatanimlama().setVisible(true);
                
            }
        });
    }
    
    public void tabloyukle(){
        int i =0;
        tablotemizle();
       for(tbloda mst: musterioda){
        satirekle();
        tbloda.setValueAt(mst.getAd(),0+i ,0 );
      tbloda.setValueAt(mst.getKat(),0+i ,2 );
        tbloda.setValueAt(mst.getKapasite(),0+i ,1 );
        tbloda.setValueAt(mst.getDurumu(),0+i ,3 );
        tbloda.setValueAt(mst.getId(),0+i ,4 );
        
        i++;    
       
       }
    }
 public void tablotemizle(){
     DefaultTableModel dmt = (DefaultTableModel)this.tbloda.getModel();
     dmt.getDataVector().removeAllElements();
      this.tbloda.repaint();
    }
  public void satirekle(){
            DefaultTableModel dmt = (DefaultTableModel)this.tbloda.getModel();
            dmt.setRowCount(dmt.getRowCount()+1);
            this.tbloda.repaint();
  }
  
  public void temizle(){
    
        txtad.setText("");
       txtkapasite.setText("");
    
    }
 public  void txtkapat(){
    txtad.setEditable(false);
    txtkapasite.setEditable(false);
   cmbkat.setEditable(false);
    cmbdurum.setEditable(false);
      txtkapasite.setBackground(new java.awt.Color(153, 153, 153));
      txtad.setBackground(new java.awt.Color(153, 153, 153));
       cmbkat.setBackground(new java.awt.Color(153, 153, 153));
      cmbdurum.setBackground(new java.awt.Color(153, 153, 153));
      
    }
 
  public void satirsil(int id){
        try {
             musterioda.remove(id);
               JOptionPane.showMessageDialog(null, "Kayıt Başırı ile silinmiştir.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "HATA!! Boş kayıt Silme İşlemi Yapamazsınız.");
        }
  }
public void txtac(){
    txtad.setEditable(true);
    txtkapasite.setEditable(true);
    cmbkat.setEditable(true);
    cmbdurum.setEditable(true);
    txtad.requestFocus();
     txtkapasite.setBackground(new java.awt.Color(255, 255, 255));
      txtad.setBackground(new java.awt.Color(255, 255, 255));
     cmbkat.setBackground(new java.awt.Color(255, 255, 255));
    cmbdurum.setBackground(new java.awt.Color(255, 255, 255));
    
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguncelle;
    private javax.swing.JButton btniptal;
    private javax.swing.JButton btnkayit;
    private javax.swing.JButton btnyenikayit;
    private javax.swing.JComboBox<String> cmbdurum;
    private javax.swing.JComboBox<String> cmbkat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMenuItemDuzenle;
    private javax.swing.JMenuItem jMenuItemSil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenuDuzenle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbloda;
    private javax.swing.JTextField txtad;
    private javax.swing.JTextField txtkapasite;
    // End of variables declaration//GEN-END:variables
}
