/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.erenresortmvn.Gui;

import com.erenresortmvn.Models.tblozellikatama;
import java.util.ArrayList;
import java.util.List;


/**
 *
 * @author cesur
 */
public class frmOdaOzellikAtama extends javax.swing.JFrame {
  
    
    
    List<tblozellikatama>  musteriodaozellik = new ArrayList<tblozellikatama>();
    /** Creates new form frmozellikatama */
    public frmOdaOzellikAtama() {
        initComponents();
         tblozellikata.setDefaultEditor(Object.class, null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnyenikayit = new javax.swing.JButton();
        btnkaydet = new javax.swing.JButton();
        btnguncelle = new javax.swing.JButton();
        btniptal = new javax.swing.JButton();
        cmbodaid = new javax.swing.JComboBox<>();
        cmbozellikid = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblozellikata = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(65, 131, 215));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Oda Adı");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Özellik Adı");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        btnyenikayit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/erenresortmvn/Media/New_50px.png"))); // NOI18N
        btnyenikayit.setText("Yeni Kayıt");
        btnyenikayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnyenikayitActionPerformed(evt);
            }
        });
        jPanel1.add(btnyenikayit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 230, 60));

        btnkaydet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/erenresortmvn/Media/Save_50px.png"))); // NOI18N
        btnkaydet.setText("Kayıt");
        btnkaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkaydetActionPerformed(evt);
            }
        });
        jPanel1.add(btnkaydet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 230, 60));

        btnguncelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/erenresortmvn/Media/Update_50px.png"))); // NOI18N
        btnguncelle.setText("Güncelle");
        jPanel1.add(btnguncelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 230, 60));

        btniptal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/erenresortmvn/Media/Cancel_50px.png"))); // NOI18N
        btniptal.setText("İptal");
        btniptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniptalActionPerformed(evt);
            }
        });
        jPanel1.add(btniptal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 230, 60));

        jPanel1.add(cmbodaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 170, 30));

        jPanel1.add(cmbozellikid, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 170, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 441));

        tblozellikata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "OdaId", "OzellikId"
            }
        ));
        jScrollPane1.setViewportView(tblozellikata);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 590, 360));

        jPanel2.setBackground(new java.awt.Color(65, 131, 215));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 0, 40, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Odaya Özellik Atama");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 600, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnkaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkaydetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnkaydetActionPerformed

    private void btnyenikayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnyenikayitActionPerformed
   btnyenikayit.setEnabled(false);
        btnkaydet.setEnabled(true);
        btniptal.setEnabled(true);        
    }//GEN-LAST:event_btnyenikayitActionPerformed

    private void btniptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniptalActionPerformed
      btnyenikayit.setEnabled(true);
    btnkaydet.setEnabled(false);
    btnguncelle.setEnabled(false);
    btniptal.setEnabled(false);
    }//GEN-LAST:event_btniptalActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
      this.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmOdaOzellikAtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmOdaOzellikAtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmOdaOzellikAtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmOdaOzellikAtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmOdaOzellikAtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguncelle;
    private javax.swing.JButton btniptal;
    private javax.swing.JButton btnkaydet;
    private javax.swing.JButton btnyenikayit;
    private javax.swing.JComboBox<String> cmbodaid;
    private javax.swing.JComboBox<String> cmbozellikid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblozellikata;
    // End of variables declaration//GEN-END:variables

}
