package com.erenresortmvn.Gui;



import com.erenresortmvn.Models.tblpersonel;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author blacke4gle
 */
public class frmPersonelKayit extends javax.swing.JFrame {
    
    //Personel listesi
    List <tblpersonel> personellistesi = new ArrayList <tblpersonel> ();
    
    // Seçilen kayıt id al
    public static int secilenid;
    public static int kayitdurumu = 0;
    /**
     * Creates new form tblpersonelkayit
     */
    public frmPersonelKayit() {
        initComponents();
        
        //Bu kodlama Tablonun değiştirilmesini engeller.
        jTable2.setDefaultEditor(Object.class, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator9 = new javax.swing.JSeparator();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        MenuSil = new javax.swing.JMenuItem();
        MenuDuzenle = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        personelkayit = new javax.swing.JLabel();
        resimekle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        ad = new javax.swing.JLabel();
        soyad = new javax.swing.JLabel();
        tckimlik = new javax.swing.JLabel();
        telefon = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtad = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtsoyad = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txttckimlik = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txttelefon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtnot = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtadres = new javax.swing.JTextArea();
        not = new javax.swing.JLabel();
        kullaniciadi = new javax.swing.JLabel();
        txtkullaniciadi = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        sifre = new javax.swing.JLabel();
        btnyenikayit = new javax.swing.JButton();
        Xcikis = new javax.swing.JLabel();
        txtsifre = new javax.swing.JPasswordField();
        btnguncelle = new javax.swing.JButton();
        btniptal = new javax.swing.JButton();
        btnkaydet = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jSeparator9.setBackground(new java.awt.Color(91, 91, 91));

        MenuSil.setText("Kaydı Sil");
        MenuSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSilActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MenuSil);

        MenuDuzenle.setText("Kaydı Düzenle");
        MenuDuzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDuzenleActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MenuDuzenle);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setForeground(new java.awt.Color(91, 91, 91));

        jPanel2.setBackground(new java.awt.Color(97, 212, 195));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        personelkayit.setBackground(new java.awt.Color(91, 91, 91));
        personelkayit.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        personelkayit.setForeground(new java.awt.Color(91, 91, 91));
        personelkayit.setText("Personel Kayıt");
        jPanel2.add(personelkayit, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 25, -1, 35));

        resimekle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/erenresortmvn/Media/Woman Man_100px.png"))); // NOI18N
        resimekle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resimekleMouseClicked(evt);
            }
        });
        jPanel2.add(resimekle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 111, 108));

        jSeparator1.setBackground(new java.awt.Color(91, 91, 91));
        jSeparator1.setForeground(new java.awt.Color(91, 91, 91));
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 146, 10));

        jSeparator2.setBackground(new java.awt.Color(91, 91, 91));
        jSeparator2.setForeground(new java.awt.Color(91, 91, 91));
        jSeparator2.setAlignmentX(1.0F);
        jSeparator2.setAlignmentY(1.0F);
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 98, 11));

        ad.setBackground(new java.awt.Color(204, 204, 204));
        ad.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        ad.setForeground(new java.awt.Color(91, 91, 91));
        ad.setText("Ad:");

        soyad.setBackground(new java.awt.Color(204, 204, 204));
        soyad.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        soyad.setForeground(new java.awt.Color(91, 91, 91));
        soyad.setText("Soyad:");

        tckimlik.setBackground(new java.awt.Color(204, 204, 204));
        tckimlik.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tckimlik.setForeground(new java.awt.Color(91, 91, 91));
        tckimlik.setText("TC Kimlik:");

        telefon.setBackground(new java.awt.Color(204, 204, 204));
        telefon.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        telefon.setForeground(new java.awt.Color(91, 91, 91));
        telefon.setText("Telefon:");

        jSeparator3.setBackground(new java.awt.Color(91, 91, 91));
        jSeparator3.setForeground(new java.awt.Color(91, 91, 91));

        txtad.setEditable(false);
        txtad.setBackground(new java.awt.Color(36, 47, 65));
        txtad.setForeground(new java.awt.Color(255, 255, 255));
        txtad.setBorder(null);

        jSeparator4.setBackground(new java.awt.Color(91, 91, 91));
        jSeparator4.setForeground(new java.awt.Color(91, 91, 91));

        txtsoyad.setEditable(false);
        txtsoyad.setBackground(new java.awt.Color(36, 47, 65));
        txtsoyad.setForeground(new java.awt.Color(255, 255, 255));
        txtsoyad.setBorder(null);

        jSeparator5.setBackground(new java.awt.Color(91, 91, 91));
        jSeparator5.setForeground(new java.awt.Color(91, 91, 91));

        txttckimlik.setEditable(false);
        txttckimlik.setBackground(new java.awt.Color(36, 47, 65));
        txttckimlik.setForeground(new java.awt.Color(255, 255, 255));
        txttckimlik.setBorder(null);

        jSeparator6.setBackground(new java.awt.Color(91, 91, 91));
        jSeparator6.setForeground(new java.awt.Color(91, 91, 91));

        txttelefon.setEditable(false);
        txttelefon.setBackground(new java.awt.Color(36, 47, 65));
        txttelefon.setForeground(new java.awt.Color(255, 255, 255));
        txttelefon.setBorder(null);

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(91, 91, 91));
        jLabel6.setText("Adres:");

        txtnot.setEditable(false);
        txtnot.setBackground(new java.awt.Color(36, 47, 65));
        txtnot.setColumns(20);
        txtnot.setForeground(new java.awt.Color(255, 255, 255));
        txtnot.setRows(5);
        jScrollPane1.setViewportView(txtnot);

        txtadres.setEditable(false);
        txtadres.setBackground(new java.awt.Color(36, 47, 65));
        txtadres.setColumns(20);
        txtadres.setForeground(new java.awt.Color(255, 255, 255));
        txtadres.setRows(5);
        jScrollPane2.setViewportView(txtadres);

        not.setBackground(new java.awt.Color(204, 204, 204));
        not.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        not.setForeground(new java.awt.Color(91, 91, 91));
        not.setText("Not:");

        kullaniciadi.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        kullaniciadi.setForeground(new java.awt.Color(91, 91, 91));
        kullaniciadi.setText("Kullanıcı Adı:");

        txtkullaniciadi.setEditable(false);
        txtkullaniciadi.setBackground(new java.awt.Color(36, 47, 65));
        txtkullaniciadi.setForeground(new java.awt.Color(255, 255, 255));
        txtkullaniciadi.setBorder(null);

        jSeparator7.setBackground(new java.awt.Color(91, 91, 91));
        jSeparator7.setForeground(new java.awt.Color(91, 91, 91));

        jSeparator8.setBackground(new java.awt.Color(91, 91, 91));
        jSeparator8.setForeground(new java.awt.Color(91, 91, 91));

        sifre.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        sifre.setForeground(new java.awt.Color(91, 91, 91));
        sifre.setText("Şifre:");

        btnyenikayit.setBackground(new java.awt.Color(97, 212, 195));
        btnyenikayit.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnyenikayit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/erenresortmvn/Media/New_50px.png"))); // NOI18N
        btnyenikayit.setText("Yeni Kayıt");
        btnyenikayit.setMaximumSize(new java.awt.Dimension(73, 33));
        btnyenikayit.setMinimumSize(new java.awt.Dimension(73, 33));
        btnyenikayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnyenikayitActionPerformed(evt);
            }
        });

        Xcikis.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Xcikis.setForeground(new java.awt.Color(97, 212, 195));
        Xcikis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Xcikis.setText("X");
        Xcikis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Xcikis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XcikisMouseClicked(evt);
            }
        });

        txtsifre.setEditable(false);
        txtsifre.setBackground(new java.awt.Color(36, 47, 65));
        txtsifre.setForeground(new java.awt.Color(255, 255, 255));
        txtsifre.setBorder(null);

        btnguncelle.setBackground(new java.awt.Color(97, 212, 195));
        btnguncelle.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnguncelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/erenresortmvn/Media/Update_50px.png"))); // NOI18N
        btnguncelle.setText("Güncelle");
        btnguncelle.setToolTipText("");
        btnguncelle.setEnabled(false);
        btnguncelle.setMaximumSize(new java.awt.Dimension(73, 33));
        btnguncelle.setMinimumSize(new java.awt.Dimension(73, 33));
        btnguncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguncelleActionPerformed(evt);
            }
        });

        btniptal.setBackground(new java.awt.Color(97, 212, 195));
        btniptal.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btniptal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/erenresortmvn/Media/Cancel_50px.png"))); // NOI18N
        btniptal.setText("İptal");
        btniptal.setEnabled(false);
        btniptal.setMaximumSize(new java.awt.Dimension(73, 33));
        btniptal.setMinimumSize(new java.awt.Dimension(73, 33));
        btniptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniptalActionPerformed(evt);
            }
        });

        btnkaydet.setBackground(new java.awt.Color(97, 212, 195));
        btnkaydet.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnkaydet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/erenresortmvn/Media/Save_50px.png"))); // NOI18N
        btnkaydet.setText("Kaydet");
        btnkaydet.setEnabled(false);
        btnkaydet.setMaximumSize(new java.awt.Dimension(73, 33));
        btnkaydet.setMinimumSize(new java.awt.Dimension(73, 33));
        btnkaydet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnkaydetMouseClicked(evt);
            }
        });

        jTable2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable2.setForeground(new java.awt.Color(36, 47, 65));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Ad", "Soyad", "Telefon", "Adres", "TC Kimlik", "Not", "Kullanıcı Adı", "Şifre"
            }
        ));
        jTable2.setComponentPopupMenu(jPopupMenu1);
        jTable2.setDragEnabled(true);
        jScrollPane4.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(kullaniciadi)
                                .addGap(10, 10, 10)
                                .addComponent(txtkullaniciadi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(soyad))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(telefon)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jSeparator6)
                                                .addComponent(txttelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(tckimlik)
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jSeparator4)
                                                    .addComponent(txtsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jSeparator5)
                                                    .addComponent(txttckimlik, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jSeparator3)
                                                    .addComponent(txtad, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(sifre)
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtsifre, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(not))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                                            .addComponent(jScrollPane1)))))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnyenikayit, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnkaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnguncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btniptal, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Xcikis, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Xcikis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ad)
                                    .addComponent(txtad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(1, 1, 1)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(soyad)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tckimlik)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txttckimlik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)
                                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txttelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telefon))
                                .addGap(1, 1, 1)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(not)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtsifre)
                                .addGap(1, 1, 1)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kullaniciadi)
                                    .addComponent(txtkullaniciadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sifre))
                                .addGap(1, 1, 1)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(194, 194, 194))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnyenikayit, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnkaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnguncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btniptal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSilActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "İlgili Kaydı Silmek İstiyormusunuz ?",
                      "UYARI", JOptionPane.YES_NO_OPTION) ;
        
        if(reply == JOptionPane.YES_OPTION){
            
            int secilen = jTable2.getSelectedRow();
            satirsil(secilen);
            tabloyukle();
        }
        else{
            JOptionPane.showMessageDialog(null, "İşlem İptal Edilmiştir.");
        }
    }//GEN-LAST:event_MenuSilActionPerformed

    private void MenuDuzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDuzenleActionPerformed
        int secilen = jTable2.getSelectedRow();
        secilenid = secilen;
        txtad.setText(jTable2.getValueAt(secilen, 0).toString());
        txtsoyad.setText(jTable2.getValueAt(secilen, 1).toString());
        txttelefon.setText(jTable2.getValueAt(secilen, 2).toString());
        txtadres.setText(jTable2.getValueAt(secilen, 3).toString());
        txttckimlik.setText(jTable2.getValueAt(secilen, 4).toString());
        txtnot.setText(jTable2.getValueAt(secilen, 5).toString());
        txtkullaniciadi.setText(jTable2.getValueAt(secilen, 6).toString());
        txtsifre.setText(jTable2.getValueAt(secilen, 7).toString());
        
                btnyenikayit.setEnabled(false);
                btnguncelle.setEnabled(true);
                btniptal.setEnabled(true);
                txtac();
                kayitdurumu = 1 ;
    }//GEN-LAST:event_MenuDuzenleActionPerformed

    private void btnkaydetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkaydetMouseClicked

        //Pojodan nesne türetimi

        if(txtad.getText().trim().equals("") || txtadres.getText().trim().equals("")
            || txtkullaniciadi.getText().trim().equals("") ||
            txtnot.getText().trim().equals("") || txtsifre.getText().trim().equals("")
            || txtsoyad.getText().trim().equals("") || txttckimlik.getText().trim().equals("")
            || txttelefon.getText().trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Gerekli Alanları Doldurmadan Kayıt İşlemi Yapılamaz");
        }

        else{
            tblpersonel personel = new tblpersonel();

            personel.setAd(txtad.getText());
            personel.setSoyad(txtsoyad.getText());
            personel.setTelefon(txttelefon.getText());
            personel.setAdres(txtadres.getText());
            personel.setTckimlik(txttckimlik.getText());
            personel.setAciklama(txtnot.getText());
            personel.setEmail(txtkullaniciadi.getText());
            personel.setSifre(txtsifre.getText());

            personellistesi.add(personel) ;

            tabloyukle();
            temizle();

            btnyenikayit.setEnabled(true);
            btnkaydet.setEnabled(false);
            btniptal.setEnabled(false);
            txtkapat();
            kayitdurumu = 0 ;
        }

    }//GEN-LAST:event_btnkaydetMouseClicked

    private void btniptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniptalActionPerformed
        temizle();

        btnyenikayit.setEnabled(true);
        btnguncelle.setEnabled(false);
        btniptal.setEnabled(false);
        btnkaydet.setEnabled(false);
        txtkapat();
        kayitdurumu = 0 ;
    }//GEN-LAST:event_btniptalActionPerformed

    private void btnguncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguncelleActionPerformed
        tblpersonel tmp = new tblpersonel();
        tmp.setAd(txtad.getText());
        tmp.setAdres(txtadres.getText());
        tmp.setEmail(txtkullaniciadi.getText());
        tmp.setAciklama(txtnot.getText());
        tmp.setSifre(txtsifre.getText());
        tmp.setSoyad(txtsoyad.getText());
        tmp.setTckimlik(txttckimlik.getText());
        tmp.setTelefon(txttelefon.getText());
        personellistesi.set(secilenid, tmp) ;
        tabloyukle();
        temizle();

        btnyenikayit.setEnabled(true);
        btnguncelle.setEnabled(false);
        btniptal.setEnabled(false);
        txtkapat();
        kayitdurumu = 0;
    }//GEN-LAST:event_btnguncelleActionPerformed

    private void XcikisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XcikisMouseClicked
        if(kayitdurumu==1){
            JOptionPane.showMessageDialog(null, "Kayit Açık durumda");
            // this.dispose();

        }
        else
            this.setVisible(false);
    }//GEN-LAST:event_XcikisMouseClicked

    private void btnyenikayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnyenikayitActionPerformed
        btnyenikayit.setEnabled(false);
        btnkaydet.setEnabled(true);
        btniptal.setEnabled(true);
        btnguncelle.setEnabled(false);
        txtac();
        kayitdurumu = 1;
    }//GEN-LAST:event_btnyenikayitActionPerformed

    private void resimekleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resimekleMouseClicked

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        if(result == JFileChooser.APPROVE_OPTION){
            String dosya = fileChooser.getSelectedFile().getAbsolutePath();
            resimekle.setIcon(new javax.swing.ImageIcon(dosya));
        }

    }//GEN-LAST:event_resimekleMouseClicked
    
    public void tabloyukle(){
        
        int i = 0;
        tablotemizle();
        for (tblpersonel object : personellistesi) {
            satirekle();
            jTable2.setValueAt(object.getAd(), 0 + i, 0);
            jTable2.setValueAt(object.getSoyad(), 0 + i, 1);
            jTable2.setValueAt(object.getTelefon(), 0 + i, 2);
            jTable2.setValueAt(object.getAdres(), 0 + i, 3);
            jTable2.setValueAt(object.getTckimlik(), 0 + i, 4);
            jTable2.setValueAt(object.getAciklama(), 0 + i, 5);
            jTable2.setValueAt(object.getEmail(), 0 + i, 6);
            jTable2.setValueAt(object.getSifre(), 0 + i, 7);
            
            i++ ;
            
        }    
    }
    
    public void tablotemizle(){
        
       DefaultTableModel dmt = (DefaultTableModel) this.jTable2.getModel();
       dmt.getDataVector().removeAllElements();
       this.jTable2.repaint();
    
    }
    
    public void satirekle(){        
        DefaultTableModel dmt = (DefaultTableModel) this.jTable2.getModel();
        dmt.setRowCount(dmt.getRowCount()+1);
        this.jTable2.repaint();                
    }
    
    public void temizle(){
        
        txtad.setText("");
        txtadres.setText("");
        txtkullaniciadi.setText("");
        txtnot.setText("");
        txtsifre.setText("");
        txtsoyad.setText("");
        txttckimlik.setText("");
        txttelefon.setText("");
        
    
    
    
    }
    
    public void satirsil(int id){
        try{
            personellistesi.remove(id);
            JOptionPane.showMessageDialog(null, "Kayıt Başarı ile Silinmiştir.");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "HATA!! Boş Kayıt Silme İşlemi Yapamazsınız...");
        }
    }
    
    public void txtac(){
        
        txtad.setEditable(true);
        txtadres.setEditable(true);
        txtkullaniciadi.setEditable(true);
        txtnot.setEditable(true);
        txtsifre.setEditable(true);
        txtsoyad.setEditable(true);
        txttckimlik.setEditable(true);
        txttelefon.setEditable(true);
        txtad.requestFocus();
            
            txtad.setBackground(new java.awt.Color(36,47,65));
            txtadres.setBackground(new java.awt.Color(36,47,65));
            txtkullaniciadi.setBackground(new java.awt.Color(36,47,65));
            txtnot.setBackground(new java.awt.Color(36,47,65));
            txtsifre.setBackground(new java.awt.Color(36,47,65));
            txtsoyad.setBackground(new java.awt.Color(36,47,65));
            txttckimlik.setBackground(new java.awt.Color(36,47,65));
            txttelefon.setBackground(new java.awt.Color(36,47,65));
            
            
            
            
    }
    
    public void txtkapat(){
        txtad.setEditable(false);
        txtadres.setEditable(false);
        txtkullaniciadi.setEditable(false);
        txtnot.setEditable(false);
        txtsifre.setEditable(false);
        txtsoyad.setEditable(false);
        txttckimlik.setEditable(false);
        txttelefon.setEditable(false);
        
            
            txtad.setBackground(new java.awt.Color(36,47,65));
            txtadres.setBackground(new java.awt.Color(36,47,65));
            txtkullaniciadi.setBackground(new java.awt.Color(36,47,65));
            txtnot.setBackground(new java.awt.Color(36,47,65));
            txtsifre.setBackground(new java.awt.Color(36,47,65));
            txtsoyad.setBackground(new java.awt.Color(36,47,65));
            txttckimlik.setBackground(new java.awt.Color(36,47,65));
            txttelefon.setBackground(new java.awt.Color(36,47,65));
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPersonelKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPersonelKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPersonelKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPersonelKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPersonelKayit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuDuzenle;
    private javax.swing.JMenuItem MenuSil;
    private javax.swing.JLabel Xcikis;
    private javax.swing.JLabel ad;
    private javax.swing.JButton btnguncelle;
    private javax.swing.JButton btniptal;
    private javax.swing.JButton btnkaydet;
    private javax.swing.JButton btnyenikayit;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel kullaniciadi;
    private javax.swing.JLabel not;
    private javax.swing.JLabel personelkayit;
    private javax.swing.JLabel resimekle;
    private javax.swing.JLabel sifre;
    private javax.swing.JLabel soyad;
    private javax.swing.JLabel tckimlik;
    private javax.swing.JLabel telefon;
    private javax.swing.JTextField txtad;
    private javax.swing.JTextArea txtadres;
    private javax.swing.JTextField txtkullaniciadi;
    private javax.swing.JTextArea txtnot;
    private javax.swing.JPasswordField txtsifre;
    private javax.swing.JTextField txtsoyad;
    private javax.swing.JTextField txttckimlik;
    private javax.swing.JTextField txttelefon;
    // End of variables declaration//GEN-END:variables
}
