package com.erenresortmvn.Models;
// Generated 02.May.2018 11:26:57 by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;




/**
 * Tblmusteriborcu generated by hbm2java
 */
@Entity
@Table
public class tblmusteriborcu  implements java.io.Serializable {

    @Id
    @SequenceGenerator(name = "tblmusteribrsq",sequenceName = "sq_tblmusteribr_id",
            allocationSize = 1,initialValue = 1)
    @GeneratedValue(generator = "tblmusteribrsq")
     private int id;
     private Integer musteriid;
     private Double borc;

    public tblmusteriborcu() {
    }

	
    public tblmusteriborcu(int id) {
        this.id = id;
    }
    public tblmusteriborcu(int id, Integer musteriid, Double borc) {
       this.id = id;
       this.musteriid = musteriid;
       this.borc = borc;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getMusteriid() {
        return this.musteriid;
    }
    
    public void setMusteriid(Integer musteriid) {
        this.musteriid = musteriid;
    }
    public Double getBorc() {
        return this.borc;
    }
    
    public void setBorc(Double borc) {
        this.borc = borc;
    }




}


