package com.erenresortmvn.Models;
// Generated 02.May.2018 11:26:57 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;




/**
 * Tblmusteri generated by hbm2java
 */
@Entity
@Table
public class tblmusteri  implements java.io.Serializable {

    @Id
    @SequenceGenerator(name = "tblmusterisq",sequenceName = "sq_tblmusteri_id",
            allocationSize = 1,initialValue = 1)
    @GeneratedValue(generator = "tblmusterisq")
     private int id;
     private String ad;
     private String soyad;
     private String tckimlik;
     private String cinsiyet;
     private String adres;
     @Column(length = 500)
     private String aciklama;
     private String resimurl;
     private String email;
     private String sifre;
     private Integer silid;

    public tblmusteri() {
    }

	
    public tblmusteri(int id) {
        this.id = id;
    }
    public tblmusteri(int id, String ad, String soyad, String tckimlik, String cinsiyet, String adres, String aciklama, String resimurl, String email, String sifre, Integer silid) {
       this.id = id;
       this.ad = ad;
       this.soyad = soyad;
       this.tckimlik = tckimlik;
       this.cinsiyet = cinsiyet;
       this.adres = adres;
       this.aciklama = aciklama;
       this.resimurl = resimurl;
       this.email = email;
       this.sifre = sifre;
       this.silid = silid;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getAd() {
        return this.ad;
    }
    
    public void setAd(String ad) {
        this.ad = ad;
    }
    public String getSoyad() {
        return this.soyad;
    }
    
    public void setSoyad(String soyad) {
        this.soyad = soyad;
    }
    public String getTckimlik() {
        return this.tckimlik;
    }
    
    public void setTckimlik(String tckimlik) {
        this.tckimlik = tckimlik;
    }
    public String getCinsiyet() {
        return this.cinsiyet;
    }
    
    public void setCinsiyet(String cinsiyet) {
        this.cinsiyet = cinsiyet;
    }
    public String getAdres() {
        return this.adres;
    }
    
    public void setAdres(String adres) {
        this.adres = adres;
    }
    public String getAciklama() {
        return this.aciklama;
    }
    
    public void setAciklama(String aciklama) {
        this.aciklama = aciklama;
    }
    public String getResimurl() {
        return this.resimurl;
    }
    
    public void setResimurl(String resimurl) {
        this.resimurl = resimurl;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSifre() {
        return this.sifre;
    }
    
    public void setSifre(String sifre) {
        this.sifre = sifre;
    }
    public Integer getSilid() {
        return this.silid;
    }
    
    public void setSilid(Integer silid) {
        this.silid = silid;
    }




}


