package com.erenresortmvn.Models;
// Generated 02.May.2018 11:26:57 by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;




/**
 * Tbloda generated by hbm2java
 */
@Table
@Entity
public class tbloda  implements java.io.Serializable {


    @Id
    @SequenceGenerator(name = "tblodasq",sequenceName = "sq_tbloda_id",
            allocationSize = 1,initialValue = 1)
    @GeneratedValue(generator = "tblodasq")
     private int id;
     private String ad;
     private String kat;
     private Integer kapasite;
     private String durumu;
     private Integer silid;

    public tbloda() {
    }

	
    public tbloda(int id) {
        this.id = id;
    }
    public tbloda(int id, String ad, String kat, Integer kapasite, String durumu, Integer silid) {
       this.id = id;
       this.ad = ad;
       this.kat = kat;
       this.kapasite = kapasite;
       this.durumu = durumu;
       this.silid = silid;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getAd() {
        return this.ad;
    }
    
    public void setAd(String ad) {
        this.ad = ad;
    }
    public String getKat() {
        return this.kat;
    }
    
    public void setKat(String kat) {
        this.kat = kat;
    }
    public Integer getKapasite() {
        return this.kapasite;
    }
    
    public void setKapasite(Integer kapasite) {
        this.kapasite = kapasite;
    }
    public String getDurumu() {
        return this.durumu;
    }
    
    public void setDurumu(String durumu) {
        this.durumu = durumu;
    }
    public Integer getSilid() {
        return this.silid;
    }
    
    public void setSilid(Integer silid) {
        this.silid = silid;
    }




}


