package com.erenresortmvn.Models;
// Generated 02.May.2018 11:26:57 by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;




/**
 * Tblozellikatama generated by hbm2java
 */
@Table
@Entity
public class tblozellikatama  implements java.io.Serializable {


     @Id
    @SequenceGenerator(name = "tblozatasq",sequenceName = "sq_tblozata_id",
            allocationSize = 1,initialValue = 1)
    @GeneratedValue(generator = "tblozatasq")
     private int id;
     private Integer odaid;
     private Integer ozellikid;
     private Integer silid;

    public tblozellikatama() {
    }

	
    public tblozellikatama(int id) {
        this.id = id;
    }
    public tblozellikatama(int id, Integer odaid, Integer ozellikid, Integer silid) {
       this.id = id;
       this.odaid = odaid;
       this.ozellikid = ozellikid;
       this.silid = silid;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getOdaid() {
        return this.odaid;
    }
    
    public void setOdaid(Integer odaid) {
        this.odaid = odaid;
    }
    public Integer getOzellikid() {
        return this.ozellikid;
    }
    
    public void setOzellikid(Integer ozellikid) {
        this.ozellikid = ozellikid;
    }
    public Integer getSilid() {
        return this.silid;
    }
    
    public void setSilid(Integer silid) {
        this.silid = silid;
    }




}


