package com.erenresortmvn.Models;
// Generated 02.May.2018 11:26:57 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Tblrezervasyon generated by hbm2java
 */
@Table
@Entity
public class tblrezervasyon  implements java.io.Serializable {


    @Id
    @SequenceGenerator(name = "tblrezvsq",sequenceName = "sq_tblrezv_id",
            allocationSize = 1,initialValue = 1)
    @GeneratedValue(generator = "tblrezvsq")
     private int id;
     private Integer odaid;
     private Integer musteriid;
     private Integer personelid;
     private Date rezervasyontarih;
     private Date giristarihi;
     private Date cikistarihi;
     private Integer gunsayisi;
     private Integer kalankisisayisi;
     private Double birimfiyat;
     private Double indirimlifiyat;
     private Double toplamfiyat;
     @Column(length = 500)
     private String aciklama;
     private Integer silid;

    public tblrezervasyon() {
    }

	
    public tblrezervasyon(int id) {
        this.id = id;
    }
    public tblrezervasyon(int id, Integer musteriid, Integer personelid, Date rezervasyontarih, Date giristarihi, Date cikistarihi, Integer gunsayisi, Integer kalankisisayisi, Double birimfiyat, Double indirimlifiyat, Double toplamfiyat, String aciklama, Integer silid) {
       this.id = id;
       this.musteriid = musteriid;
       this.personelid = personelid;
       this.rezervasyontarih = rezervasyontarih;
       this.giristarihi = giristarihi;
       this.cikistarihi = cikistarihi;
       this.gunsayisi = gunsayisi;
       this.kalankisisayisi = kalankisisayisi;
       this.birimfiyat = birimfiyat;
       this.indirimlifiyat = indirimlifiyat;
       this.toplamfiyat = toplamfiyat;
       this.aciklama = aciklama;
       this.silid = silid;
    }
   
    
    
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getMusteriid() {
        return this.musteriid;
    }
    
    public void setMusteriid(Integer musteriid) {
        this.musteriid = musteriid;
    }
    public Integer getPersonelid() {
        return this.personelid;
    }
    
    public void setPersonelid(Integer personelid) {
        this.personelid = personelid;
    }
    public Date getRezervasyontarih() {
        return this.rezervasyontarih;
    }
    
    public void setRezervasyontarih(Date rezervasyontarih) {
        this.rezervasyontarih = rezervasyontarih;
    }
    public Date getGiristarihi() {
        return this.giristarihi;
    }
    
    public void setGiristarihi(Date giristarihi) {
        this.giristarihi = giristarihi;
    }
    public Date getCikistarihi() {
        return this.cikistarihi;
    }
    
    public void setCikistarihi(Date cikistarihi) {
        this.cikistarihi = cikistarihi;
    }
    public Integer getGunsayisi() {
        return this.gunsayisi;
    }
    
    public void setGunsayisi(Integer gunsayisi) {
        this.gunsayisi = gunsayisi;
    }
    public Integer getKalankisisayisi() {
        return this.kalankisisayisi;
    }
    
    public void setKalankisisayisi(Integer kalankisisayisi) {
        this.kalankisisayisi = kalankisisayisi;
    }
    public Double getBirimfiyat() {
        return this.birimfiyat;
    }
    
    public void setBirimfiyat(Double birimfiyat) {
        this.birimfiyat = birimfiyat;
    }
    public Double getIndirimlifiyat() {
        return this.indirimlifiyat;
    }
    
    public void setIndirimlifiyat(Double indirimlifiyat) {
        this.indirimlifiyat = indirimlifiyat;
    }
    public Double getToplamfiyat() {
        return this.toplamfiyat;
    }
    
    public void setToplamfiyat(Double toplamfiyat) {
        this.toplamfiyat = toplamfiyat;
    }
    public String getAciklama() {
        return this.aciklama;
    }
    
    public void setAciklama(String aciklama) {
        this.aciklama = aciklama;
    }
    public Integer getSilid() {
        return this.silid;
    }
    
    public void setSilid(Integer silid) {
        this.silid = silid;
    }

    public Integer getOdaid() {
        return odaid;
    }

    public void setOdaid(Integer odaid) {
        this.odaid = odaid;
    }




}


